// export const lightTheme = {
//   palette: {
//     themePrimary: '#09d3ac',
//     themeLighterAlt: '#000807',
//     themeLighter: '#01221b',
//     themeLight: '#033f33',
//     themeTertiary: '#057f67',
//     themeSecondary: '#07ba96',
//     themeDarkAlt: '#1dd8b3',
//     themeDark: '#3cdebe',
//     themeDarker: '#6be7ce',
//     neutralLighterAlt: '#ffffff',
//     neutralLighter: '#ffffff',
//     neutralLight: '#ffffff',
//     neutralQuaternaryAlt: '#ffffff',
//     neutralQuaternary: '#ffffff',
//     neutralTertiaryAlt: '#ffffff',
//     neutralTertiary: '#0b0b0b',
//     neutralSecondary: '#0f0f0f',
//     neutralPrimaryAlt: '#131313',
//     neutralPrimary: '#212121',
//     neutralDark: '#1a1a1a',
//     black: '#1e1e1e',
//     white: '#ffffff',
//   }
// };

export const darkTheme = {
  palette: {
    themePrimary: '#09d3ac',
    themeLighterAlt: '#f4fdfb',
    themeLighter: '#d2f8f0',
    themeLight: '#acf2e4',
    themeTertiary: '#61e5cb',
    themeSecondary: '#22d9b4',
    themeDarkAlt: '#08be9a',
    themeDark: '#06a182',
    themeDarker: '#057760',
    neutralLighterAlt: '#2b2b2b',
    neutralLighter: '#333333',
    neutralLight: '#414141',
    neutralQuaternaryAlt: '#4a4a4a',
    neutralQuaternary: '#515151',
    neutralTertiaryAlt: '#6f6f6f',
    neutralTertiary: '#c8c8c8',
    neutralSecondary: '#d0d0d0',
    neutralPrimaryAlt: '#dadada',
    neutralPrimary: '#ffffff',
    neutralDark: '#f4f4f4',
    black: '#f8f8f8',
    white: '#212121',
  }
}